mirakurun:
  build: mirakurun
  cap_add:
   - SYS_ADMIN
   - SYS_NICE
   - SYS_RAWIO
  container_name: mirakurun
  devices:
   - /dev/asv52200:/dev/asv52200
   - /dev/asv52201:/dev/asv52201
   - /dev/asv52202:/dev/asv52202
   - /dev/asv52203:/dev/asv52203
   - /dev/bus/usb:/dev/bus/usb
  ports:
    - "40772:40772"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./mirakurun/conf:/usr/local/etc/mirakurun
   - ./mirakurun/db:/usr/local/var/db/mirakurun
  restart: always

chinachu:
  build: chinachu
  container_name: chinachu
  ports:
   - "10772:10772"
   - "20772:20772"
   - "5353:5353/udp"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./chinachu/conf/config.json:/usr/local/chinachu/config.json
   - ./chinachu/conf/rules.json:/usr/local/chinachu/rules.json
   - ./chinachu/data:/usr/local/chinachu/data
   - /var/lib/chinachu/recorded:/usr/local/chinachu/recorded
  links:
   - mirakurun:container-mirakurun
  restart: always
